services:
  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./etc/rabbitmq/data:/var/lib/rabbitmq

  mongo:
    image: mongo:8.0
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./etc/mongo:/data/db
    networks:
      - api_net

  redis:
    image: redis:7.2
    restart: always
    command: redis-server --requirepass password
    ports:
      - 6379:6379
    volumes:
      - ./etc/redis:/data/db
    networks:
      - api_net

  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./etc/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local

  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - ./etc/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: local
      MYSQL_PASSWORD: password

  qdrant:
    image: qdrant/qdrant
    ports:
      - '6333:6333'
    volumes:
      - ./etc/qdrant:/var/lib/qdrant

networks:
  api_net:
    driver: bridge
